### ISSUE TITLE
Entities have some properties and methods generated twise

### ISSUE THREAD

**Issue by hollax** [api-platform/schema-generator#114]
Some of the entities have some properties and methods generated twice. What am i doing wrong?
i used *allProperties: true* in the configuration for these entities

**Comment by stefann-sasori** [comment]
Same here. Any helps ?

**Comment by stefann-sasori** [comment]
Hello,

I found that this issue occurs when an entity has both a plural and singular form of a given property.
For example: [Cemetery](https://schema.org/Cemetery) has these properties:
   - event
   - events (superseded by event)

or 
   - map
   - maps (superseded by map)

Both of such properties are generated by the generator.
However: all non array property names are singularized before the generation
https://github.com/api-platform/schema-generator/blob/14c4e2e3ac1b139c517dbb8e0a875c9387c4ebfd/src/TypesGenerator.php#L651

so that in the case of the Cemetery entity:
- "events" will be transformed to "event" causing the duplication of the "event" property.

As I assume that it makes sense to "pluralize" an array property, I wonder why it is necessary to "singularize" all the non array properties.
Many string properties in schema.org are written with a plural form when they are meant to contain multiple values separated by a comma within a string. These are for example: https://schema.org/keywords, https://schema.org/maps ...

It seemed to work when I fixed it this way: 
![image](https://user-images.githubusercontent.com/11821158/44564798-82e5f480-a754-11e8-91db-db5379d578d9.png)

**Comment by dunglas** [comment]
Closed by #153
