### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by KDederichs** [api-platform/schema-generator#418]
Hey,

since Symfony 7 support is now merged in, could you maybe tag a new release with that?

Thanks!

**Comment by ovidiuenache** [comment]
Hey,

There's a problem with the Symfony 7 support because of the `cebe/php-openapi` package.

As you can see below, the latest version supports `symfony/yaml` up to version 6
![image](https://github.com/api-platform/schema-generator/assets/20539991/92f6f365-adc6-4c30-978e-76797ce7159b)

I checked the repository and if you take a look at [this issue](https://github.com/cebe/php-openapi/issues/190) it seems that things are moving a bit slowly lately.

I created two issues there ([200](https://github.com/cebe/php-openapi/issues/200) and [200](https://github.com/cebe/php-openapi/issues/201)) and the [PR](https://github.com/cebe/php-openapi/pull/202) to fix them.
I'll follow those threads and come back with a reply if/when it gets merged.

We might need to consider an alternative if nothing happens and the package stays outdated.

**Comment by SpartakusMd** [comment]
Maybe we could start thinking about switching the library? From what I see https://packagist.org/packages/devizzent/cebe-php-openapi is having pretty active development.

**Comment by franz-josef-kaiser** [comment]
As everybody (including me) seems to have that problem: Could we please have some proposal of the solution? Thanks in advance.

**Comment by dunglas** [comment]
Maybe could we switch to this fork? https://github.com/DEVizzent/cebe-php-openapi

**Comment by franz-josef-kaiser** [comment]
@dunglas This is the one I currently forked to be able to use as a drop-in replacement (as this only works, when the repo uses the same `name` in `composer.json`). It works perfect.

```bash
{
  // …
  "cebe/php-openapi": "dev-master as 1.7.x-dev",
  // …
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/<$NAME>/php-openapi.git"
    }
  ]
  // …
}
  ```

**Comment by soyuka** [comment]
https://github.com/api-platform/schema-generator/pull/425 how's that?

**Comment by franz-josef-kaiser** [comment]
Will try to find some time during the weekend and check. Thanks for jumping in @soyuka .

**Comment by SpartakusMd** [comment]
I prepared the necessary changes in #426. Not sure what to do with the OpenApi 3.1 where the type may be a list of types. Added a TODO for the moment.

**Comment by paul-crashley** [comment]
When is the actual tag coming?

**Comment by soyuka** [comment]
done
